# Generated by Django 5.0.3 on 2024-04-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sdpid', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('data', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
    ]
